config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    member do
      resources :albums, only: [:new] do
        member do
          resources :tracks, only: [:new]
        end
      end
    end
  end

  resources :albums, except: [:new]
  resources :tracks, except: [:new]
  resources :notes, except: [:new, :index, :show]

  root to:'bands#index'

end

app/models/track.rb
class Track < ActiveRecord::Base
  TRACK_TYPE = %w(Standard Bonus)
  #validations
  validates :name, :album_id, :ord, :track_type, presence: true
  validates :ord, uniqueness: {scope: :album_id}
  validates :track_type, inclusion: { in: TRACK_TYPE}
  #associations
  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :valid_view?

  def index
    @tracks = Track.all
                    .joins("JOIN albums on album_id = albums.id JOIN bands ON band_id = bands.id")
                    .order("bands.name, albums.title, tracks.ord")
                    .page params[:page]
  end

  def show
    @track = Track.find_by_id(params[:id])
    @album = Album.find_by_id(@track.album_id)
    @band = Band.find_by_id(@album.band_id)
    @notes = Note.where(track_id: @track.id).order("updated_at DESC")
    @note_route = notes_url
  end

  def create
    @track = Track.new(track_params)
    @albums = Album.all
    @album = Album.find_by_id(params[:track][:album_id])
    @band = Band.find_by_id(@album.band_id)
    @route = tracks_url

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @track.errors.full_messages
      render :new
    end
  end

  def new
    @track = Track.new
    @albums = Album.all
    @album = Album.find_by_id(params[:id])
    @band = Band.find_by_id(@album.band_id)
    @route = tracks_url
  end


  def destroy
    @track = Track.find_by_id(params[:id])
    @album = Album.find_by_id(@track.album_id)
    if @track.destroy
      flash[:errors] ||= []
      flash[:errors] += ["#{@track.name} deleted successfully"]
      redirect_to album_url(@album)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @track.errors.full_messages
      render track_url(@track)
    end
  end

  def edit
    @track = Track.find_by_id(params[:id])
    @albums = Album.all
    @album = Album.find_by_id(@track.album_id)
    @band = Band.find_by_id(@album.band_id)
    @route = track_url(@track)
  end

  def update
    @track = Track.find_by_id(params[:id])
    @albums = Album.all
    @album = Album.find_by_id(@track.album_id)
    @band = Band.find_by_id(@album.band_id)
    @route = tracks_url

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @track.errors.full_messages
      render :edit
    end
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :ord, :track_type, :lyrics)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    lyrics = lyrics.split(".")
    lyrics[0] = " #{lyrics.first}"
    lyrics.map!{|l| "♫ #{l}"}
    "<pre>#{lyrics.join(". \n")}</pre>".html_safe
  end
end

app/views/tracks/_form.html.erb
<form action="<%= @route %>" method="post">
  <% unless @track.id.nil? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>


  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Name</span>
    <input type="text" name="track[name]" value="<%= @track.name %>" class="form-control" aria-describedby="basic-addon1">
  </div>

  </br>

  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Album</span>
      <select name="track[album_id]" class="form-control" aria-describedby="basic-addon1">
        <% @albums.each do |album| %>
          <option value="<%= album.id %>"
              <% if album == @album %>
                selected
              <% end %>>
            <%= album.title %>
          </option>
        <% end %>
      </select>
    </label>
  </div>

  </br>

  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Ord</span>
    <input type="text" name="track[ord]" value="<%= @track.ord %>" class="form-control" aria-describedby="basic-addon1">
  </div>

  </br>

  <h5>Track type</h5>

  <label class="radio-inline">
    <input type="radio" name="track[track_type]" value="Standard"
                    <% if "Standard" == @track.track_type %>
                      checked
                    <% end %>>
    Standard
  </label>
  <label class="radio-inline"></label>
    <input type="radio" name="track[track_type]" value="Bonus"
                    <% if "Bonus" == @track.track_type %>
                      checked
                    <% end %>>
    Bonus
  </label>

  </br>
  </br>

  <h5>Lyrics</h5>
  <div class="form-group">
    <textarea name="track[lyrics]" rows="8" cols="40" class="form-control"><%= @track.lyrics %></textarea>
  </div>

  </br>

  <% submit_text = @track.id.nil? ? "Add Track" : "Update Track" %>
  <input type="submit" value="<%= submit_text %>" class="btn btn-primary">
</form>

app/views/tracks/edit.html.erb
<h1>Edit <%= @track.name %></h1>

<%= render "form" %>

app/views/tracks/index.html.erb
<h1 class="index_header">Tracks</h1>
<%= paginate @tracks, window: 2 %>

<table class="table" data-sortable>
  <thead>
    <tr>
      <th>Track</th>
      <th>Track Type</th>
      <th>Album</th>
      <th>Band</th>
      <th>Year</th>
    </tr>
</thead>
<tbody>
    <% @tracks.each do |track| %>
    <tr>
      <td><%= link_to short(track.name), track_url(track) %></td>
      <td><%= track.track_type %></td>
      <td><%= link_to track.album.title, album_url(track.album_id) %></td>
      <td><%= link_to track.band.name, band_url(track.album.band_id) %></td>
      <td><%= track.album.year %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tracks/new.html.erb
<h1>Add a new track</h1>

<%= render "form" %>

app/views/tracks/show.html.erb
<div class="background-header center-header">
  <h1><%= @track.name %></h1>
  by the band
  <h2> <%= @band.name %> </h2>
  on the album
  <h3><%= @album.title %></h3>
</div>

<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <%= button_to "Edit Track", edit_track_url(@track), method: :get, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Delete Track", track_url(@track), method: :delete, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Back to #{@album.title}", album_url(@album), method: :get, class: "btn btn-default" %>
  </div>
</div>

<h3>Lyrics</h3>
<%=  ugly_lyrics(@track.lyrics) %>


<h3>Notes</h3>

<%= render "notes/note", notes: @notes %>
<%= render "notes/form", route: @note_route,
                         track: @track%>