config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    member do
      resources :albums, only: [:new] do
        member do
          resources :tracks, only: [:new]
        end
      end
    end
  end

  resources :albums, except: [:new]
  resources :tracks, except: [:new]
  resources :notes, except: [:new, :index, :show]

  root to:'bands#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  RECORDING_TYPE = %w(Live Studio)

  #validaitons
  validates :band_id, :title, :recording_type, :year, presence: true
  validates :title, uniqueness: {scope: :band_id}
  validates :recording_type, inclusion: {in: RECORDING_TYPE}
  #associations
  belongs_to :band

  has_many :tracks, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :valid_view?

  def index
    @albums = Album.all
                   .joins("JOIN bands ON band_id = bands.id")
                   .order("bands.name, title")
                   .page params[:page]
  end

  def create
    @album = Album.new(album_params)
    @bands = Band.all
    @band = Band.find_by_id(@album.band_id)
    @route = tracks_url

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @album.errors.full_messages
      render :new
    end
  end

  def new
    @album = Album.new
    @bands = Band.all
    @band = Band.find_by_id(params[:id])
    @route = albums_url
  end

  def show
    @album = Album.find_by_id(params[:id])
    @band = Band.find_by_id(@album.band_id)
    @tracks = @album.tracks
  end

  def destroy
    @album = Album.find_by_id(params[:id])
    @band = Band.find_by_id(@album.band_id)
    if @album.destroy
      flash[:errors] ||= []
      flash[:errors] += ["#{@album.title} deleted successfully"]
      redirect_to band_url(@band)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @album.errors.full_messages
      render album_url(@album)
    end
  end

  def edit
    @album = Album.find_by_id(params[:id])
    @bands = Band.all
    @band = Band.find_by_id(@album.band_id)
    @route = album_url(@album)
  end

  def update
    @album = Album.find_by_id(params[:id])
    @bands = Band.all
    @band = Band.find_by_id(@album.band_id)
    @route = tracks_url

    if @album.update(album_params)
      redirect_to album_url(@update)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @album.errors.full_messages
      render :edit
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :recording_type, :year)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<form action="<%= @route %>" method="post">
  <% unless @album.id.nil? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>


  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Title</span>
    <input type="text" name="album[title]" value="<%= @album.title %>" class="form-control" aria-describedby="basic-addon1">
  </div>

  </br>

  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Band</span>
      <select name="album[band_id]" class="form-control" aria-describedby="basic-addon1">
        <% @bands.each do |band| %>
          <option value="<%= band.id %>"
              <% if band == @band %>
                selected
              <% end %>>
            <%= band.name %>
          </option>
        <% end %>
      </select>
    </label>
  </div>

  </br>

  <h5>Album Type </h5>
  <label class="radio-inline">
    <input type="radio" name="album[recording_type]" value="Live"
            <% if "Live" == @album.recording_type %>
              checked
            <% end %>>
    Live
  </label>
  <label class="radio-inline">
    <input type="radio" name="album[recording_type]" value="Studio"
            <% if "Studio" == @album.recording_type %>
              checked
            <% end %>>
    Studio
  </label>

  </br>
  </br>

  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Year</span>
    <input type="text" name="album[year]" value="<%= @album.year %>" class="form-control" aria-describedby="basic-addon1">
  </div>

  </br>

  <% submit_text = @album.id.nil? ? "Add Album" : "Update Album" %>
  <input type="submit" value="<%= submit_text %>" class="btn btn-primary">
</form>

app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %> </h1>

<%= render "form" %>

app/views/albums/index.html.erb
<h1 class="index_header">Albums</h1>
<%= paginate @albums, window: 2 %>

<table class="table" data-sortable>
  <thead>
    <tr>
      <th>Album</th>
      <th>Band</th>
      <th>Year</th>
    </tr>
</thead>
<tbody>
  <% @albums.each do |album| %>
    <tr>
      <td><%=link_to album.title, album_url(album) %></td>
      <td><%=link_to album.band.name, band_url(album.band_id) %></td>
      <td><%= album.year %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/albums/new.html.erb
<h1>Add a new Album</h1>

<%= render "form" %>

app/views/albums/show.html.erb
<div class="background-header center-header">
  <h1><%= @album.title %></h1>
  by the band
  <h2> <%= @band.name %> </h2>
</div>

<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <%= button_to "New Track", new_track_url, method: :get, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Edit Album", edit_album_url(@album), method: :get, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Delete Album", album_url(@album), method: :delete, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Back to #{@band.name}", band_url(@band), method: :get, class: "btn btn-default" %>
  </div>
</div>


<h3>Tracks</h3>
<div class="list-group">
  <% @tracks.each do |track| %>
      <%= link_to track.name, track_url(track), class: "list-group-item" %>
  <% end %>
</div>