config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    member do
      resources :albums, only: [:new] do
        member do
          resources :tracks, only: [:new]
        end
      end
    end
  end

  resources :albums, except: [:new]
  resources :tracks, except: [:new]
  resources :notes, except: [:new, :index, :show]

  root to:'bands#index'

end

app/models/band.rb
class Band < ActiveRecord::Base
  #validations
  validates :name, presence: true, uniqueness: true
  #associations
  has_many :albums, dependent: :destroy


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :valid_view?

  def index
    @bands = Band.all
                 .order("name")
                 .page params[:page]
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
    @route = bands_url
  end

  def show
    @band = Band.find_by_id(params[:id])
    @albums = @band.albums
  end

  def destroy
    @band = Band.find_by_id(params[:id])
    if @band.destroy
      flash[:errors] ||= []
      flash[:errors] += ["#{@band.name} deleted successfully"]
      redirect_to bands_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @band.errors.full_messages
      render band_url(@band)
    end
  end

  def edit
    @band = Band.find_by_id(params[:id])
    @route = band_url
  end

  def update
    @band = Band.find_by_id(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @band.errors.full_messages
      render :edit
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<form action="<%= @route %>" method="post">
  <% unless @band.id.nil? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>

  <div class="input-group">
    <span class="input-group-addon" id="sizing-addon2">Name</span>
    <input type="text" name="band[name]" value="<%= @band.name %>" class="form-control" aria-describedby="basic-addon1">
  </div>

  </br>

  <% submit_text = @band.id.nil? ? "Add Band" : "Update Band" %>
  <input type="submit" value="<%= submit_text %>" class="btn btn-primary">
</form>

app/views/bands/edit.html.erb
<h1>Update <%= @band.name %></h1>

<%= render "form" %>

app/views/bands/index.html.erb
<h1 class="index_header">Bands</h1>
<%= paginate @bands, window: 2 %>



<table class="table" data-sortable>
<thead>
  <tr>
    <th>
      <%= link_to "New Band", new_band_url, class: "list-group-item list-group-item-success" %>
    </br>
      Sort Names On Page
    </th>
  </tr>
</thead>
<tbody>
    <% @bands.each do |band| %>
    <tr>
    <td>
      <%= link_to band.name, band_url(band), type: "button" %>
    </td>
  </tr>
    <% end %>
  </tbody>
</table>

app/views/bands/new.html.erb
<h1>Add a new band!!</h1>

<%= render "form" %>

app/views/bands/show.html.erb
<div class="background-header center-header">
  <h1><%= @band.name %></h1>
</div>

<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <%= button_to "New Album", new_album_url, method: :get, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Edit Band", edit_band_url(@band), method: :get, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Delete Band", band_url(@band), method: :delete, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "All Bands", bands_url, method: :get, class: "btn btn-default" %>
  </div>
</div>



<h3>Albums</h3>
<div class="list-group">
  <% @albums.each do |album| %>
      <%= link_to album.title, album_url(album), class: "list-group-item" %>
  <% end %>
</div>