config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    member do
      resources :albums, only: [:new] do
        member do
          resources :tracks, only: [:new]
        end
      end
    end
  end

  resources :albums, except: [:new]
  resources :tracks, except: [:new]
  resources :notes, except: [:new, :index, :show]

  root to:'bands#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag    'sortable-theme-dark' %>
  <%= javascript_include_tag 'sortable.min.js' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <% unless flash[:errors].nil? %>
  <div class="bs-callout bs-callout-danger" id="errors">
    <% flash[:errors].each do |error| %>
    <h4><%= error %></h4>
    <% end %>
  </div>
  <% end %>
  <div id="wrapper">

    <div id="sidebar-wrapper">

      <nav class="sidebar-nav">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <a href='<%= bands_url %>'>
              <img src='https://s4.postimg.org/l0gr7qmct/logo.png' border='0' alt='logo'/>
            </a>
          </li>
          <% if logged_in? %>
          <li class="center"><%= link_to current_user.email, user_url(current_user) %></li>
          <li>
            <div class="btn-group btn-group-justified" role="group">
              <div class="btn-group" role="group">
                <%= button_to "Log Out", session_url, method: :delete, class: "btn btn-default"%>
              </div>
            </div>
          </li>
          <li><%= link_to "Bands", bands_url, method: :get %></li>
          <li><%= link_to "Albums", albums_url, method: :get %></li>
          <li><%= link_to "Tracks", tracks_url, method: :get %></li>
        </ul>
        <% else %>
        <li>
          <div class="btn-group btn-group-justified" role="group">
            <div class="btn-group" role="group">
              <%= button_to "Sign In", new_session_url, method: :get, class: "btn btn-default" %>
            </div>
            <div class="btn-group" role="group">
              <%= button_to "Sign Up", new_user_url, method: :get, class: "btn btn-default" %>
            </div>
          </div>
        </li>
      </ul>
      <% end %>
    </nav>
  </div>
  <div id="page-content-wrapper">
    <%= yield %>
  </div>


</div>
</body>
</html>